In [1]:
import cvxpy as cvx
import numpy as np
import pandas as pd

from time import time

# Setup

Initialise PRNG.

In [2]:
prng = np.random.RandomState(seed=42)

Set number of items.

In [3]:
n_items = 50

Sample random values and weights.

In [4]:
items = pd.DataFrame({
    'value': prng.randn(n_items),
    'weight': prng.randn(n_items)
})

In [5]:
items.head()

value    weight
0  0.496714  0.324084
1 -0.138264 -0.385082
2  0.647689 -0.676922
3  1.523030  0.611676
4 -0.234153  1.031000

# Modelling

Define the binary decision variables representing whether each item should be included in the solution.

In [6]:
x = cvx.Variable(n_items, boolean=True)

Define the total capacity.

In [7]:
capacity = 100

Define and solve the problem of maximising total value subject to the capacity constraint.

In [8]:
problem = cvx.Problem(
    cvx.Maximize(x * items['value']),
    [x * items['weight'] <= capacity]
)

In [9]:
problem.solve()

13.523770625995027

Check the solution.

In [10]:
x.value.astype(int)

array([0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0])

Define a function to solve a random knapsack problem for `n_items` items and return the time it took.

In [11]:
def time_random_knapsack_solution(n_items):
    values = prng.randn(n_items)
    weights = prng.randn(n_items)
    x = cvx.Variable(n_items, boolean=True)
    problem = cvx.Problem(cvx.Maximize(x * values), [x * weights <= capacity])
    start_time = time()
    problem.solve()
    return time() - start_time

Run `time_random_knapsack_solution` for increasingly larger `n_items`.

In [12]:
n_items = np.asarray([100, 1000, 10000, 100000])

In [13]:
times = np.asarray([time_random_knapsack_solution(x) for x in n_items])

In [14]:
times

array([9.29164886e-03, 1.79336071e-02, 2.07066536e-01, 1.41861026e+01])

In [15]:
times[1:] / times[:-1]

array([ 1.930078  , 11.54628485, 68.50987565])